# Generated by Django 4.1.2 on 2023-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="weather", name="temperature",),
        migrations.AddField(
            model_name="weather",
            name="DayHumidity",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weather", name="DayTemp", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weather",
            name="NightHumidity",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weather", name="NightTemp", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weather", name="WindSpeed", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weather",
            name="guess_weather",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weather",
            name="real_weather",
            field=models.IntegerField(null=True),
        ),
    ]
