# Generated by Django 4.1.2 on 2023-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_weather_temperature_weather_dayhumidity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="Loc",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
